GET http://www.mocky.io/v2/5de6b9253700005f000925b8

 {"indicator":[
{
    "number": 1.1,
    "title": "Create mathematical expressions to describe physical phenomena (or a physical problem)."
},
{
    "number": 1.2,
    "title": "Select and describe appropriate tools to solve mathematical problems that arise from modeling physical phenomena."
},

{
    "number": 1.3,
    "title": "Use solution to mathematical problems to inform the (real-world problem) that gave rise to it."
},
{
    "number": 1.4,
    "title": "Identify fundamental scientific and engineering principles that govern the performance of a given process or system."
},
{
    "number": 1.5,
    "title": "Recall and describe fundamental concepts in natural sciences."
}
{
    "number": 2.1,
    "title": "Create processes for solving problems including justified approximations and assumptions.."
},
{
    "number": 2.2,
    "title": "Evaluate validity of results and model for error/uncertainty."
},

{
    "number": 2.3,
    "title": "Reframe complex problems into interconnected sub-problems, using a systems approach."
},
{
    "number": 2.4,
    "title": "Identify known and unknown information, uncertainties, and biases in complex ill-structured problems"
}
{
    "number": 3.1,
    "title": "Generate working hypotheses and assumptions for engineering problems."
},
{
    "number": 3.2,
    "title": "Develop investigations involving information and data gathering, analysis, and/or experimentation."
},

{
    "number": 3.3,
    "title": "Analyze and interpret data and information to reach a conclusion using a systems approach."
},
{
    "number": 3.4,
    "title": "Identify limitations of the tests and methods used and their impact on the results."
}
{
    "number": 4.1,
    "title": "Follow a general procedure to design a system, component, or process for a complex open-ended problem."
},
{
    "number": 4.2,
    "title": "Identify client and user needs."
},

{
    "number": 4.3,
    "title": "Evaluate the design options against project criteria using a systems approach."
},
{
    "number": 4.4,
    "title": "Assess design based on requirements, yield, reliability, safety, and impact on environment and society."
},
{
    "number": 4.5,
    "title": "Create and test simulations, models, and/or prototypes of the design."
},
{
    "number": 4.6,
    "title": "Incorporate client/user feedback into the design."
}
{
"number": 5.1,
"title": "Select appropriate measurement devices or techniques to accomplish a task."
},
{
"number": 5.2,
"title": "Demonstrate correct usage of testing apparatus, databases, models, and/or standards."
},

{
"number": 5.3,
"title": "Analyze the limitations, uncertainties, and sources of error inherent in engineering tools."
},
{
"number": 5.4,
"title": "Evaluate appropriateness of results from instrumentation, measurements techniques, models and simulations"
}
]
}