GET http://localhost:3000/kb

###

GET http://localhost:3000/kb/5de08db062516739d4aba464

###

POST http://localhost:3000/kb
Content-Type: application/json

{
    "number" : 1,
    "title" : "testing name",
    "description" : "testing description",
    "sub_ga" :[{
        "number" : 1.1,
        "title" : "sub_ga"  
    }]
}

###

DELETE http://localhost:3000/kb/5de08dce1e70363e3ca9ed95

###

PATCH  http://localhost:3000/kb/5de08dce1e70363e3ca9ed95
Content-Type: application/json

{
    "title": "New  Title"
}

###

DELETE http://localhost:3000/kb